export const projects = [
  {
    id: '1',
    screenshot: '/logo.png',
    title: 'aperture-ui',
    subTitle: 'A HTML/CSS/JS Library for Games',
    stack: [
      'C++',
      'Boost',
      'Yoga',
      'WDFoundation',
      'DirectX',
      'PS5',
      'Xbox Series X',
    ],
    description: `Aperture UI is a HTML/CSS/JS library that allows you to create user interfaces for games. I made this library to give a more web compliant version to RmlUi & Give an open-source option to Coherent Labs Gameface Middleware. This project was a feat in itself as it forced me to learn alot more about advanced algorithms & data-structures for parsing the DOM, it reinforced my Multithreading Skills, since i had to work with V8, and many more single-thread & non-thread-safe libraries. Networking was also a big part of this project as i had to create a way to communicate with the game engine, and the UI. This project is still in development, but it is already being used in a few games at WD Studios Corp.`,
    date: 'Dec 5, 2024',
    github: 'https://github.com/WatchDogStudios/ApertureUI',
    live: 'https://site.apertureui.tech/',
    color: 'rgba(249,115,22)',
    btnBg: 'rgba(154,52,18,0.5)',
    btnBgHover: 'rgba(67,20,7)',
    cardBg: 'rgba(154,52,18,0.05)',
  },
  {
    id: '2',
    screenshot: '/CASS_LOGO_CORE_BLACK.png',
    title: 'Cassandra',
    subTitle: 'Open Source Rust based Server Management System',
    stack: [
      'Rust',
      'typescript',
      'tailwindcss',
      'tokio',
      'ci/cd',
      'aws',
    ],
    description:
      'Cassandra is a Rust-based server management system designed to simplify the deployment and management of servers. The platform allows users to create, monitor, and manage servers with ease, providing a seamless experience for developers and administrators. The application is built with Rust, TypeScript, and Tailwind CSS, and leverages Tokio for asynchronous programming. Continuous integration and deployment (CI/CD) pipelines are set up using GitHub Actions, ensuring fast and reliable deployments. The application is hosted on AWS for high availability and scalability.',
    date: 'Nov 19, 2024',
    github: 'https://github.com/WatchDogStudios/CassandraNet',
    live: 'https://site.cassandranet.tech/',
    color: 'rgba(139,92,246)',
    btnBg: 'rgba(91,33,182,0.5)',
    btnBgHover: 'rgba(46,16,101)',
    cardBg: 'rgba(91,33,182,0.05)',
  },
  {
    id: '3',
    screenshot: '/RAGE_UE_BANNER.png',
    title: 'RAGE Battleground Chronicles',
    subTitle: 'A Community Driven, Modible Anime Styled Fighting Game.',
    stack: [
      'Unreal Engine 5',
      'C++',
      'Blueprints',
      'Azure Playfab',
      'Replication',
      "Blender",
      'AngelScript',
    ],
    description:
      'NOTE: Github Shows the Extensible UI Repo, NOT Game Code. RAGE Battleground Chronciles is a moddible fighting game that allows players to create their own characters, stages, and moves. The game is built with Unreal Engine 5, C++, and Blueprints, and features a unique anime-inspired art style. Azure PlayFab is used for backend services, including player authentication, leaderboards, and matchmaking. The game supports replication for multiplayer gameplay, enabling players to compete against each other in real-time. Blender is used for 3D modeling and animation, while AngelScript is used for scripting custom moves and abilities.',
    date: 'Sep 2, 2024',
    github: 'https://github.com/WatchDogStudios/RAGEBGC-UI',
    live: 'https://wdstudios.tech/rage-battleground-chronicles',
    color: 'rgba(79,70,229)',
    btnBg: 'rgba(55,48,163,0.5)',
    btnBgHover: 'rgba(30,27,75)',
    cardBg: 'rgba(55,48,163,0.05)',
  },
  {
    id: '4',
    screenshot: '/profile.png',
    title: 'WD Studios Corp',
    subTitle: 'An Game Development Corporation',
    stack: ['react', 'tailwindcss', 'framer motion', 'shadcn','c++','rust'],
    description: `WD Studios Corp is a game development corporation that specializes in creating high-quality games for a global audience. We are dedicated to delivering immersive and engaging gaming experiences that captivate players and push the boundaries of creativity.`,
    date: 'Jan 2, 2024',
    github: '',
    live: 'https://wdstudios.tech/',
    color: 'rgba(34,197,94)',
    btnBg: 'rgba(22,101,52,0.5)',
    btnBgHover: 'rgba(5,46,22)',
    cardBg: 'rgba(22,101,52,0.05)',
  },
  {
    id: '5',
    screenshot: '/download.jpg',
    title: 'Advanced Worlds Engine (A.W.E)',
    subTitle: 'An AAA, Open Source Game Engine (Heavily Modified Fork of DagorEngine)',
    stack: ['vulkan', 'directx', 'qt', 'c++', 'python', 'lua', 'aws', 'c#'],
    description: `AWE is an open-source AAA game engine that provides developers with the tools and resources they need to create high-quality games. The engine supports Vulkan and DirectX for graphics rendering, Qt for user interface development, and C++, Python, and Lua for scripting. AWS is used for cloud services, including storage, compute, and networking. AWE is WD Studios' internal fork of the DagorEngine, which includes custom features and optimizations for our needs like A New Physics Engine, Better World Building Tools, Lightmapping Tools, a new Hair & Fur System, and many more.`,
    date: 'Dec 10, 2024',
    github: '',
    live: '',
    color: 'rgba(6,182,212)',
    btnBg: 'rgba(7,89,133,0.5)',
    btnBgHover: 'rgba(8,47,73)',
    cardBg: 'rgba(7,89,133,0.05)',
  },
  {
    id: '6',
    screenshot: '/download.jpg',
    title: 'ArbitorVM',
    subTitle: 'A IL2CPP VM For Games. Planned to be Open Sourced Soon.',
    stack: [ 'c++', 'IL', 'c#'],
    description: `ArbitorVM is a high-performance virtual machine designed specifically for game development, serving as an advanced IL2CPP runtime that bridges managed and native code execution. This project represents a significant leap in game engine architecture, providing developers with the flexibility of C# scripting while maintaining the performance characteristics critical for AAA game development. The VM features advanced JIT compilation, garbage collection optimizations tailored for real-time applications, and seamless integration with native game engine systems. Currently used internally at WD Studios for our next-generation game projects, ArbitorVM is planned to be open-sourced to benefit the broader game development community.`,
    date: 'Dec 10, 2024',
    github: '',
    live: '',
    color: 'rgba(6,182,212)',
    btnBg: 'rgba(7,89,133,0.5)',
    btnBgHover: 'rgba(8,47,73)',
    cardBg: 'rgba(7,89,133,0.05)',
  }
];
